obstacle_range: 2.0
raytrace_range: 5.0
footprint: [[0.20, 0.20], [0.20, -0.20], [-0.30, -0.20], [-0.30, 0.20]] 
transform_tolerance : 0.2

#plugins:
#      - {name: static_layer,       type: "costmap_2d::StaticLayer"}
#      - {name: obstacle_layer_kinect,        type: "costmap_2d::VoxelLayer"}
#      - {name: obstacle_layer_laser,       type: "costmap_2d::VoxelLayer"}
#      - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}


observation_sources: scan
scan: {sensor_frame: pioneer1/camera_depth_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.4}
