obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.70
footprint: [[-0.23,-0.23],[-0.23,0.23], [0.23, 0.23], [0.23,-0.23]]
transform_tolerance : 0.2
map_type: costmap
#plugins:
#      - {name: static_layer,       type: "costmap_2d::StaticLayer"}
#      - {name: obstacle_layer_kinect,        type: "costmap_2d::VoxelLayer"}
#      - {name: obstacle_layer_laser,       type: "costmap_2d::VoxelLayer"}
#      - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}


observation_sources: scan
scan: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
