local_costmap:
  global_frame: /pioneer2/odom
  robot_base_frame: /pioneer2/base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  publish_cost_grid: true
  inflation_radius: 2.0
  cost_scaling_factor: 5.0
